name: jdalrymple
favicon: null
layout_spectrum: 0.24473
typography_spectrum: 0.1534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#471c58'
    - '#000000'
    - '#ffffff'
    - '#808080'
    - '#d2ccd5'
  brandStrength: 0.29571390617638826
  lightness: 0.5750111546367407
  saturation: 0.27633315371349454
  rhythmicContrast: 0.23323752102442086
purpose: []
